### ISSUE TITLE
background color

### ISSUE THREAD

**Issue by aurelien45** [FredBardin/phpMyHue#10]
hello,
I am looking for a way to change the background color of the interface, but I don't find which file I have to modify and I don't have very good knowledge in HTML/CSS/JS.
I already try to modify the /themes/Style.css file but it done nothing.
Can you hlp me ?

**Comment by FredBardin** [comment]
Hello,
It's really not an easy thing if you'r not familiar with this.
The interfac'e is build on jquery-ui which offers some preset theme and it's what I used.

If you're looking at the css used, you'll find them into /js/jquery-ui but don't think about a full revamping. There're a lot of parameter and some graphical objects used too. 

Hope you'll find what you're looking for ;)

**Comment by aurelien45** [comment]
I try to modify the theme using the link in the jquery-ui.css file, but it's not working.
thank you for the answer even if i don't succeed i learn something today ;)

**Comment by FredBardin** [comment]
Yes, style of jquery-ui elements are not easy to modify.
The backgound alone is in the the theme/style.css (background-color) but it's the smallest part of the css.
