### ISSUE TITLE
Undefined index: xy

### ISSUE THREAD

**Issue by HVSoftware** [FredBardin/phpMyHue#11]
Got this message:

Notice: Undefined index: xy in C:\web\phpMyHue\include\huecolor.php on line 122

PHP 7.2.0

**Comment by FredBardin** [comment]
Hello,

Thanks for your report.

This is obviously not normal, but I need more details.

Could you please indicate the type of lamp you're using ? (select the lamp, then 'informations' in right panel)

**Comment by HVSoftware** [comment]
I will do so.

I had issue with GitHub today, otherwise you already had a pull request.



Op ma 22 okt. 2018 19:08 schreef FredBardin <notifications@github.com>:

**Comment by HVSoftware** [comment]
I've go this error with a light and a switch:


```
Group id: 1
Type: LightGroup
```


```
Group id: 4
Type: Room
Effect: undefined
```

I've also retrieved the JSON 

```
{
	"state": {
		"on": false,
		"bri": 190,
		"ct": 443,
		"alert": "select",
		"colormode": "ct",
		"mode": "homeautomation",
		"reachable": true
	},
	"swupdate": {
		"state": "noupdates",
		"lastinstall": "2017-11-19T19:18:56"
	},
	"type": "Color temperature light",
	"name": "Badkamer",
	"modelid": "LTW001",
	"manufacturername": "Philips",
	"productname": "Hue ambiance lamp",
	"capabilities": {
		"certified": true,
		"control": {
			"mindimlevel": 2000,
			"maxlumen": 806,
			"ct": {
				"min": 153,
				"max": 454
			}
		},
		"streaming": {
			"renderer": false,
			"proxy": false
		}
	},
	"config": {
		"archetype": "sultanbulb",
		"function": "functional",
		"direction": "omnidirectional"
	},
	"uniqueid": "------",
	"swversion": "5.105.0.21536"
}
```

I have found the cause - will make a PR. I could not find other places where this error occurred.

**Comment by FredBardin** [comment]
Ok, got it.

CT lamp are not fully managed (a dev is in progress) and I can't really test it (don't have this type of lamp). 

There's a test with type "Color Temperature Light" instead of "Color temperature light" ('t' and 'l' in lowercase ...).

I'll push the current dev for CT as fix and let you tell me what is the result

**Comment by FredBardin** [comment]
Close issue as it's fully related to CT management enhancement issue
