### ISSUE TITLE
HTML Format Proposals For 13714ec

### ISSUE THREAD

**Issue by OneOfTheInfiniteMonkeys** [FredBardin/phpMyHue#15]
Salut,
  I think there may be issues with the HTML, 
I amended my downloaded instance, specifcally the </HEAD> tag was moved to directly above the <BODY> tag. 

May I propose the HTML is passed though a HTML validator.
e.g.
https://validator.w3.org/#validate_by_input

</head> might extend to encompass the style and script elements
Propose change the HTML tags to lower case e.g. <head> as opposed to <HEAD>
Propose remove the forward slash '/' from the closing tags /> where its not needed and so on

Using it on a Raspberry Pi with around 30 lights. The intent is to take the basis of this code and integrate it into my own Home Management Software.

Cordialement et Merci
OneOfTheInfiniteMonkeys

**Comment by FredBardin** [comment]
Hello,

Indeed, there's an error from the beginning with the </head> which was strangely not at its normal location.

It's corrected in dev, the <head> block is now complete and correct, thanks.
'/>' in <meta> is also removed (don't know why I put it, perhaps too much xml seen at this moment).

For uppercase tags, it's an old habit I have, not an issue even it the current standards prefer to put all the syntax in lowercase.

Your remarks are welcome and I'm glad to see this big amount of connected lights in your home, I don't have so much.
Feel free to add any comment, thank you again.

Fred

**Comment by OneOfTheInfiniteMonkeys** [comment]
Github seemed to exclude the HTML text tags I put in to be helpfull as it treats them as markup. Apologies if this made issue identification less clear than it might have been.

Thanks for putting the script together and actively maintaining the project.

Stay safe.
OneOfTheInfiniteMonkeys
