### ISSUE TITLE
ksort errors under PHP 8 (with fix)

### ISSUE THREAD

**Issue by freebrowser1** [FredBardin/phpMyHue#16]
The functions loadNameIndex() and loadGroupsLightsNameIndex() in include/hueapi.php issue errors when ksort reaches a NULL value. PHP 8 has stricter type checking.

I fixed that locally by 

        if (is_array($this->info[$idxname])) {
		    ksort($this->info[$idxname]);
        }

and 
            if (is_array($this->info['groups'][$gnum]['lightsnames'])) {
		        ksort($this->info['groups'][$gnum]['lightsnames']);
            }

and it worked under PHP 8.0.0.

**Comment by FredBardin** [comment]
Hello,

Thank you for reporting the issue.
I don't have empty lists in my configuration and forgot to check the code against null value :(  

I'll fix that asap.

**Comment by FredBardin** [comment]
Corrections included into v1.7.4
