### ISSUE TITLE
Philips Hue White error

### ISSUE THREAD

**Issue by mladensantic** [FredBardin/phpMyHue#6]
Hello!
I just bought Philips Hue White and after running phpMyHue folowing error occurs.

Notice: Undefined index: xy in phpMyHue\include\huecolor.php on line 120

Thank you.

Mladen

**Comment by FredBardin** [comment]
Hello,

Thanks for you report.

Indeed, white dimmable light has obvioulsy less parameters and capabilities that the color ones and it wasn't tested (I don't have one). 

I need to make a full analysis of the differences to manage them correctly both in code and interface and deliver a complete correction (probably next week).

**Comment by mladensantic** [comment]
Great :)
Thank you.
Mladen

**Comment by FredBardin** [comment]
Hello,

I pushed a correction on master branch v1.4.1.
For your problem, **you only need to update file "include/huecolor.php"** (I'll do a tag later if it's ok).

Normally, the white lights must be now correctly managed, but I don't prevent a user from trying some color update actions like changing a color, launching a colorloop, etc.
So far I tested these actions (I can only simulate white light), you can perhaps receive an error message from hue bridge but there'll be no more error in the interface.

Can you install the correction and give me a feedback with a real device ?

**Comment by mladensantic** [comment]
Hello!
Great :)
It works :)
No error for now :)
Thank you for great work.

Mladen

**Comment by FredBardin** [comment]
Perfect, good news :)

I created the new release with the correction and I close this issue
